### PR TITLE
It Should work now

### PR DESCRIPTION
**Pull request by bestplay9384**
Let me know if anything works as you expected :D IMHO everything's ok

### CODE REVIEW

**Comment by xsibix** [comment]
Looks good. Well done fixing the getLocalPosition from ClientSoldier. Did you reclassed it?

**Comment by bestplay9384** [comment]
I was trying to build it all on dumped and fixed offsets, but the whole work done in Mem class would be copied in all places. I dont have enough experience in c++ so i decided just to make it work for now (it looks like UC society cannot live without it xD)

**Comment by xsibix** [comment]
Yeah, thats right... how ever, just a tip if you're wandering about the changed mouse cursor ingame: comment all usages of imGui out in dx11.cpp render routine and you'll see wonders.. unfortunately I have not much time to spent more time for that issue.. (it can be an issue if the mousecursor is visible in the ff-shots)

**Comment by bestplay9384** [comment]
Good to know mate! I will check it

**Pull request merged**
